CREATE  DATABASE IF NOT EXISTS PARTSCORP;
USE PARTSCORP;

CREATE TABLE PARTSCORP (
 ORDERID INT PRIMARY KEY,
 CUSTOMER_NAME VARCHAR (100) ,
 REGION VARCHAR (50),
 ORDER_AMOUNT INT NOT NULL,
 QUANTITY VARCHAR(50)
 );
 ALTER TABLE PARTSCORP 
 RENAME TO INVOICE;
 
 INSERT INTO PARTSCORP VALUES
 (101, "TECH CORP", "EAST", 1200, 5),
 (102, "GLOBAL INC", "WEST", 450, 2),
 (103,"TECH CORP", "EAST", 800, 4),
 (104, "APEX LTD", "NORTH", 300, 1),
 (105, "GLOBAL INC", "WEST", 1500, 6),
 (106, "APEX LTD", "NORTH", 700, 3),
 (107, "TECH CORP", "EAST", 150, 1);
 
 
 SELECT * FROM INVOICE;
 -- QUES
 -- FIND THE TOTAL SALES AMOUNT FOR EACH CUSTOMER NAME, BUT ONLY FOR ORDERS WHERE THE ORDERAMOUNT IS GREATER THAN 200.
 -- FUTHERMORE ONLY SHOW CUSTOMERS WHOSE TOTAL SALES EXCEED 1000.
 
 -- ANS
 SELECT SUM(ORDER_AMOUNT) , CUSTOMER_NAME AS BUYER FROM  INVOICE
 WHERE ORDER_AMOUNT > 200 -- THROW AWAY SMALL INDIVIDUAL ORDERS.
GROUP BY CUSTOMER_NAME -- PUT REMAINING ORDERS INTO THE BUCKET.
HAVING SUM(ORDER_AMOUNT) > 1000; -- KEEP ONLY BUCKETS WITH A TOTAL OVER 1000
 
 